// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjqcfgleswintrjzrhnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcWNmZ2xlc3dpbnRyanpyaG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzk2MDQsImV4cCI6MjA1OTc1NTYwNH0.UYAZvbkgLgfk1OG1vYUjp2GZ8hqrPr6pQOhXP6J3K9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);